services:
  - type: web
    name: my-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build  # Path to your built static assets

  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    routes:
      - name: user-login
        path: /user/login
        healthCheckPath: /

    cors:
      allow_origin: 'http://localhost:3000'  # Allow requests from your frontend
      allow_methods: 'GET, POST, PUT, DELETE, OPTIONS'
      allow_headers: 'X-Requested-With, Content-Type, Authorization'
